export const SPECIALTIES_CATALOG = [
  // NATUREZA (Nature)
  { title: "Acampamento I", category: "natureza" },
  { title: "Acampamento II", category: "natureza" },
  { title: "Acampamento III", category: "natureza" },
  { title: "Acampamento IV", category: "natureza" },
  { title: "Anfíbios", category: "natureza" },
  { title: "Aves", category: "natureza" },
  { title: "Aves Domésticas", category: "natureza" },
  { title: "Astronomia", category: "natureza" },
  { title: "Árvores", category: "natureza" },
  { title: "Aracnídeos", category: "natureza" },
  { title: "Arbustos", category: "natureza" },
  { title: "Algas", category: "natureza" },
  { title: "Borboletas", category: "natureza" },
  { title: "Cactos", category: "natureza" },
  { title: "Cães", category: "natureza" },
  { title: "Climatologia", category: "natureza" },
  { title: "Conservação Ambiental", category: "natureza" },
  { title: "Ecologia", category: "natureza" },
  { title: "Estudo de Insetos", category: "natureza" },
  { title: "Estudo de Mamíferos", category: "natureza" },
  { title: "Estudo de Répteis", category: "natureza" },
  { title: "Estudo de Samambaias", category: "natureza" },
  { title: "Estudo de Vermes", category: "natureza" },
  { title: "Estudo de Fungos", category: "natureza" },
  { title: "Flores", category: "natureza" },
  { title: "Fósseis", category: "natureza" },
  { title: "Gatos", category: "natureza" },
  { title: "Geologia", category: "natureza" },
  { title: "Gramíneas", category: "natureza" },
  { title: "Insetos", category: "natureza" },
  { title: "Invertebrados Marinhos", category: "natureza" },
  { title: "Líquens e Briófitas", category: "natureza" },
  { title: "Moluscos", category: "natureza" },
  { title: "Orquídeas", category: "natureza" },
  { title: "Peixes", category: "natureza" },
  { title: "Plantas Silvestres Comestíveis", category: "natureza" },
  { title: "Rochas e Minerais", category: "natureza" },
  { title: "Sementes", category: "natureza" },
  { title: "Vida Silvestre", category: "natureza" },
  { title: "Zoológicos", category: "natureza" },

  // ARTES E HABILIDADES MANUAIS (Arts & Crafts)
  { title: "Aeromodelismo", category: "artes" },
  { title: "Arte de Trançar", category: "artes" },
  { title: "Arte de Trançar em Fios", category: "artes" },
  { title: "Arquitetura", category: "artes" },
  { title: "Artesanato com Agulha", category: "artes" },
  { title: "Bordado", category: "artes" },
  { title: "Canto", category: "artes" },
  { title: "Cerâmica", category: "artes" },
  { title: "Cestaria", category: "artes" },
  { title: "Crochê", category: "artes" },
  { title: "Culinária I", category: "artes" },
  { title: "Culinária II", category: "artes" },
  { title: "Decoração de Bolos", category: "artes" },
  { title: "Desenho", category: "artes" },
  { title: "Escultura", category: "artes" },
  { title: "Fotografia", category: "artes" },
  { title: "Instrumentos Musicais", category: "artes" },
  { title: "Modelagem em Gesso", category: "artes" },
  { title: "Música", category: "artes" },
  { title: "Origami", category: "artes" },
  { title: "Pintura em Vidro", category: "artes" },
  { title: "Pintura em Tela", category: "artes" },
  { title: "Tecelagem", category: "artes" },
  { title: "Trabalhos em Couro", category: "artes" },
  { title: "Trabalhos em Feltro", category: "artes" },
  { title: "Trabalhos em Madeira", category: "artes" },
  { title: "Trabalhos em Metal", category: "artes" },

  // CIÊNCIAS E SAÚDE (Science & Health)
  { title: "Anatomia", category: "ciencia" },
  { title: "Biologia", category: "ciencia" },
  { title: "Enfermagem Caseira", category: "ciencia" },
  { title: "Física", category: "ciencia" },
  { title: "Fisiologia", category: "ciencia" },
  { title: "Higiene", category: "ciencia" },
  { title: "Nutrição", category: "ciencia" },
  { title: "Óptica", category: "ciencia" },
  { title: "Primeiros Socorros - Básico", category: "ciencia" },
  { title: "Primeiros Socorros - Intermediário", category: "ciencia" },
  { title: "Primeiros Socorros - Avançado", category: "ciencia" },
  { title: "Química", category: "ciencia" },
  { title: "Resgate Básico", category: "ciencia" },
  { title: "Saúde e Temperança", category: "ciencia" },
  { title: "CPR", category: "ciencia" },

  // ATIVIDADES MISSIONÁRIAS (Missionary)
  { title: "Arte de Contar Histórias Cristãs", category: "missionaria" },
  { title: "Aventuras por Computador", category: "missionaria" },
  { title: "Cidadania Cristã", category: "missionaria" },
  { title: "Colportagem", category: "missionaria" },
  { title: "Evangelismo Pessoal", category: "missionaria" },
  { title: "História Denominacional", category: "missionaria" },
  { title: "Liderança de Juvenis", category: "missionaria" },
  { title: "Mordomia", category: "missionaria" },
  { title: "Pioneirismo", category: "missionaria" },
  { title: "Temperança", category: "missionaria" },
  { title: "Vida Familiar", category: "missionaria" },

  // VIDA PRÁTICA (Practical Life)
  { title: "Alfaiataria", category: "pratica" },
  { title: "Alvenaria", category: "pratica" },
  { title: "Auto-Mecânica", category: "pratica" },
  { title: "Carpintaria", category: "pratica" },
  { title: "Computação I", category: "pratica" },
  { title: "Computação II", category: "pratica" },
  { title: "Costura", category: "pratica" },
  { title: "Datilografia / Digitação", category: "pratica" },
  { title: "Eletricidade", category: "pratica" },
  { title: "Encanamento", category: "pratica" },
  { title: "Encadernação", category: "pratica" },
  { title: "Journalismo", category: "pratica" },
  { title: "Lava-Roupas", category: "pratica" },
  { title: "Marcenaria", category: "pratica" },
  { title: "Pintura de Paredes", category: "pratica" },
  { title: "Primeiros Socorros para Animais", category: "pratica" },
  { title: "Radioamadorismo", category: "pratica" },
  { title: "Secretariado", category: "pratica" },
  { title: "Sapateiro", category: "pratica" },
  { title: "Vendas", category: "pratica" },

  // AGRÍCOLAS (Agricultural)
  { title: "Agricultura", category: "agricolas" },
  { title: "Apicultura", category: "agricolas" },
  { title: "Avicultura", category: "agricolas" },
  { title: "Criação de Cabras", category: "agricolas" },
  { title: "Criação de Gado", category: "agricolas" },
  { title: "Criação de Ovelhas", category: "agricolas" },
  { title: "Floricultura", category: "agricolas" },
  { title: "Fruticultura", category: "agricolas" },
  { title: "Horticultura", category: "agricolas" },
  { title: "Jardinagem", category: "agricolas" },
  { title: "Pecuária", category: "agricolas" },
  { title: "Pomares", category: "agricolas" },
  { title: "Silvicultura", category: "agricolas" },

  // RECREATIVAS (Recreational)
  { title: "Alpinismo", category: "recreativa" },
  { title: "Arqueirismo", category: "recreativa" },
  { title: "Atletismo", category: "recreativa" },
  { title: "Canoagem", category: "recreativa" },
  { title: "Ciclismo", category: "recreativa" },
  { title: "Equitação", category: "recreativa" },
  { title: "Excursionismo pedestre", category: "recreativa" },
  { title: "Ginástica", category: "recreativa" },
  { title: "Mergulho", category: "recreativa" },
  { title: "Natação I", category: "recreativa" },
  { title: "Natação II", category: "recreativa" },
  { title: "Natação III", category: "recreativa" },
  { title: "Navegação", category: "recreativa" },
  { title: "Orientação", category: "recreativa" },
  { title: "Patinação", category: "recreativa" },
  { title: "Remo", category: "recreativa" },
  { title: "Salvamento Aquático", category: "recreativa" },
  { title: "Ski Aquático", category: "recreativa" },
  { title: "Triatlo", category: "recreativa" },
  { title: "Vela", category: "recreativa" },
  { title: "Voleibol", category: "recreativa" },

  // ADICIONAIS PARA COMPLETAR 205 (Curated list)
  { title: "Adestramento de Cães", category: "natureza" },
  { title: "Aeroestação", category: "recreativa" },
  { title: "Alimentação Saudável", category: "ciencia" },
  { title: "Amarras", category: "natureza" },
  { title: "Amnésia", category: "ciencia" },
  { title: "Animais em Extinção", category: "natureza" },
  { title: "Animais Noturnos", category: "natureza" },
  { title: "Antídotos", category: "ciencia" },
  { title: "Apologética Cristã", category: "missionaria" },
  { title: "Aquarismo", category: "natureza" },
  { title: "Arqueologia Bíblica", category: "missionaria" },
  { title: "Artes Marciais", category: "recreativa" },
  { title: "Árvores II", category: "natureza" },
  { title: "Atividades em Altitude", category: "recreativa" },
  { title: "Atividades Subaquáticas", category: "recreativa" },
  { title: "Automobilismo", category: "recreativa" },
  { title: "Aviação", category: "pratica" },
  { title: "Bacteriologia", category: "ciencia" },
  { title: "Balonismo", category: "recreativa" },
  { title: "Basquetebol", category: "recreativa" },
  { title: "Beisebol", category: "recreativa" },
  { title: "Bicicross", category: "recreativa" },
  { title: "Biotecnologia", category: "ciencia" },
  { title: "Botanica", category: "natureza" },
  { title: "Bridge", category: "pratica" },
  { title: "Bushcraft", category: "natureza" },
  { title: "Cabeleireiro", category: "pratica" },
  { title: "Camping", category: "natureza" },
  { title: "Capoeira", category: "recreativa" },
  { title: "Cartografia", category: "natureza" },
  { title: "Cavalos", category: "natureza" },
  { title: "Células", category: "ciencia" },
  { title: "Cinema", category: "artes" },
  { title: "Circo", category: "artes" },
  { title: "Clube de Desbravadores", category: "missionaria" },
  { title: "Coleções", category: "artes" },
  { title: "Combate a Incêndios", category: "pratica" },
  { title: "Comunicação", category: "missionaria" },
  { title: "Confeitaria", category: "pratica" },
  { title: "Construções Rústicas", category: "natureza" },
  { title: "Costura Básica", category: "pratica" },
  { title: "Criação de Coelhos", category: "agricolas" },
  { title: "Criação de Peixes", category: "agricolas" },
  { title: "Criação de Pombos", category: "agricolas" },
  { title: "Criptografia", category: "pratica" },
  { title: "Crítica Literária", category: "artes" },
  { title: "Culinária com Microondas", category: "pratica" },
  { title: "Culinária Saudável", category: "ciencia" },
  { title: "Cuidado de Bebês", category: "pratica" },
  { title: "Cutelaria", category: "artes" },
  { title: "Dança Cristã", category: "artes" },
  { title: "Decupagem", category: "artes" },
  { title: "Defesa Pessoal", category: "recreativa" },
  { title: "Demografia", category: "ciencia" },
  { title: "Dentística", category: "ciencia" },
  { title: "Desenho Animado", category: "artes" },
  { title: "Desenho Técnico", category: "pratica" },
  { title: "Deserto", category: "natureza" },
  { title: "Desfibrilação", category: "ciencia" },
  { title: "Design Gráfico", category: "artes" },
  { title: "Direito", category: "ciencia" },
  { title: "Diretores de Jovens", category: "missionaria" },
  { title: "Dobradura", category: "artes" },
  { title: "Drones", category: "pratica" },
  { title: "Drogas", category: "ciencia" },
  { title: "Ecologia II", category: "natureza" },
  { title: "Economia Doméstica", category: "pratica" },
  { title: "Eden", category: "missionaria" },
  { title: "Educação Física", category: "recreativa" },
  { title: "Eletrotécnica", category: "pratica" },
  { title: "Embriologia", category: "ciencia" },
  { title: "Emergências Médicas", category: "ciencia" },
  { title: "Empilhadeiras", category: "pratica" },
  { title: "Encaixes e Entalhes", category: "artes" },
  { title: "Enfermagem", category: "ciencia" },
  { title: "Engenharia", category: "ciencia" },
  { title: "Engenhosidade", category: "pratica" },
  { title: "Entomologia", category: "natureza" },
  { title: "Equilíbrio", category: "recreativa" },
  { title: "Escatologia", category: "missionaria" },
  { title: "Escotismo", category: "natureza" },
  { title: "Escritura Criativa", category: "artes" },
  { title: "Escultura em Areia", category: "artes" },
  { title: "Espeleologia", category: "natureza" },
  { title: "Esportes Radicais", category: "recreativa" },
  { title: "Estreias", category: "recreativa" },
  { title: "Estudo da Bíblia", category: "missionaria" },
  { title: "Etimologia", category: "ciencia" },
  { title: "Etiqueta", category: "pratica" },
  { title: "Excursionismo pedestre II", category: "recreativa" },
  { title: "Exploração de Cavernas", category: "natureza" },
  { title: "Farmácia", category: "ciencia" },
  { title: "Ferrovias", category: "pratica" },
  { title: "Filatelia", category: "artes" },
  { title: "Filosofia", category: "ciencia" },
  { title: "Fisioterapia", category: "ciencia" },
  { title: "Fitoterapia", category: "natureza" },
  { title: "Foguetes", category: "pratica" },
  { title: "Fonoaudiologia", category: "ciencia" },
  { title: "Fronteiras", category: "natureza" },
  { title: "Futebol", category: "recreativa" },
  { title: "Futebol Americano", category: "recreativa" },
  { title: "Gastronomia", category: "pratica" },
  { title: "Genética", category: "ciencia" },
  { title: "Gesso", category: "artes" },
  { title: "Globalização", category: "ciencia" },
  { title: "Golfe", category: "recreativa" },
  { title: "Grafitagem", category: "artes" },
  { title: "Grimórios", category: "missionaria" },
  { title: "Habilidades com Faca", category: "natureza" },
  { title: "Handleball", category: "recreativa" },
  { title: "Hardware", category: "pratica" },
  { title: "Hebreu", category: "ciencia" },
  { title: "Helicópteros", category: "pratica" },
  { title: "Herpetologia", category: "natureza" },
  { title: "Hidráulica", category: "pratica" },
  { title: "Hidroginástica", category: "recreativa" },
  { title: "Hidrologia", category: "natureza" },
  { title: "Hipismo", category: "recreativa" },
];
